name: Friday Build
on:
  schedule:
    # Run every friday at 05:50UTC/08:50MSK
    - cron: '50 5 * * 5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60263be67e0972a2d9368874
