name: Trigger Netlify Build
on:
  schedule:
    # Run at 0815 daily
      - cron: '25 9 * * 5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60263be67e0972a2d9368874
